// Full currency catalog ported verbatim from js/app.js `currencyInfo` (line 260).
// ~155 currencies with flag emoji, full name, and symbol.

export interface CurrencyInfo {
  code: string;
  flag: string;
  name: string;
  symbol: string;
}

export const CURRENCY_INFO: Record<string, { flag: string; name: string; symbol: string }> = {
  ZAR: { flag: '🇿🇦', name: 'South African Rand', symbol: 'R' },
  USD: { flag: '🇺🇸', name: 'US Dollar', symbol: '$' },
  EUR: { flag: '🇪🇺', name: 'Euro', symbol: '€' },
  GBP: { flag: '🇬🇧', name: 'British Pound', symbol: '£' },
  NGN: { flag: '🇳🇬', name: 'Nigerian Naira', symbol: '₦' },
  KES: { flag: '🇰🇪', name: 'Kenyan Shilling', symbol: 'KSh' },
  GHS: { flag: '🇬🇭', name: 'Ghanaian Cedi', symbol: 'GH₵' },
  INR: { flag: '🇮🇳', name: 'Indian Rupee', symbol: '₹' },
  BRL: { flag: '🇧🇷', name: 'Brazilian Real', symbol: 'R$' },
  JPY: { flag: '🇯🇵', name: 'Japanese Yen', symbol: '¥' },
  AUD: { flag: '🇦🇺', name: 'Australian Dollar', symbol: 'A$' },
  CAD: { flag: '🇨🇦', name: 'Canadian Dollar', symbol: 'C$' },
  CNY: { flag: '🇨🇳', name: 'Chinese Yuan', symbol: '¥' },
  BWP: { flag: '🇧🇼', name: 'Botswana Pula', symbol: 'P' },
  MZN: { flag: '🇲🇿', name: 'Mozambican Metical', symbol: 'MT' },
  CHF: { flag: '🇨🇭', name: 'Swiss Franc', symbol: 'CHF' },
  SEK: { flag: '🇸🇪', name: 'Swedish Krona', symbol: 'kr' },
  NOK: { flag: '🇳🇴', name: 'Norwegian Krone', symbol: 'kr' },
  NZD: { flag: '🇳🇿', name: 'New Zealand Dollar', symbol: 'NZ$' },
  SGD: { flag: '🇸🇬', name: 'Singapore Dollar', symbol: 'S$' },
  HKD: { flag: '🇭🇰', name: 'Hong Kong Dollar', symbol: 'HK$' },
  MXN: { flag: '🇲🇽', name: 'Mexican Peso', symbol: 'Mex$' },
  EGP: { flag: '🇪🇬', name: 'Egyptian Pound', symbol: 'E£' },
  TZS: { flag: '🇹🇿', name: 'Tanzanian Shilling', symbol: 'TSh' },
  UGX: { flag: '🇺🇬', name: 'Ugandan Shilling', symbol: 'USh' },
  RWF: { flag: '🇷🇼', name: 'Rwandan Franc', symbol: 'RF' },
  XOF: { flag: '🌍', name: 'West African CFA', symbol: 'CFA' },
  AED: { flag: '🇦🇪', name: 'UAE Dirham', symbol: 'AED' },
  ARS: { flag: '🇦🇷', name: 'Argentine Peso', symbol: 'AR$' },
  BDT: { flag: '🇧🇩', name: 'Bangladeshi Taka', symbol: '৳' },
  CLP: { flag: '🇨🇱', name: 'Chilean Peso', symbol: 'CL$' },
  COP: { flag: '🇨🇴', name: 'Colombian Peso', symbol: 'CO$' },
  CZK: { flag: '🇨🇿', name: 'Czech Koruna', symbol: 'Kč' },
  DKK: { flag: '🇩🇰', name: 'Danish Krone', symbol: 'kr' },
  HUF: { flag: '🇭🇺', name: 'Hungarian Forint', symbol: 'Ft' },
  IDR: { flag: '🇮🇩', name: 'Indonesian Rupiah', symbol: 'Rp' },
  ILS: { flag: '🇮🇱', name: 'Israeli Shekel', symbol: '₪' },
  KRW: { flag: '🇰🇷', name: 'South Korean Won', symbol: '₩' },
  KWD: { flag: '🇰🇼', name: 'Kuwaiti Dinar', symbol: 'KD' },
  MYR: { flag: '🇲🇾', name: 'Malaysian Ringgit', symbol: 'RM' },
  PEN: { flag: '🇵🇪', name: 'Peruvian Sol', symbol: 'S/' },
  PHP: { flag: '🇵🇭', name: 'Philippine Peso', symbol: '₱' },
  PKR: { flag: '🇵🇰', name: 'Pakistani Rupee', symbol: 'Rs' },
  PLN: { flag: '🇵🇱', name: 'Polish Zloty', symbol: 'zł' },
  QAR: { flag: '🇶🇦', name: 'Qatari Riyal', symbol: 'QR' },
  RON: { flag: '🇷🇴', name: 'Romanian Leu', symbol: 'lei' },
  RUB: { flag: '🇷🇺', name: 'Russian Ruble', symbol: '₽' },
  SAR: { flag: '🇸🇦', name: 'Saudi Riyal', symbol: 'SR' },
  THB: { flag: '🇹🇭', name: 'Thai Baht', symbol: '฿' },
  TRY: { flag: '🇹🇷', name: 'Turkish Lira', symbol: '₺' },
  TWD: { flag: '🇹🇼', name: 'Taiwan Dollar', symbol: 'NT$' },
  UAH: { flag: '🇺🇦', name: 'Ukrainian Hryvnia', symbol: '₴' },
  VND: { flag: '🇻🇳', name: 'Vietnamese Dong', symbol: '₫' },
  XAF: { flag: '🌍', name: 'Central African CFA', symbol: 'FCFA' },
  AFN: { flag: '🇦🇫', name: 'Afghan Afghani', symbol: '؋' },
  ALL: { flag: '🇦🇱', name: 'Albanian Lek', symbol: 'L' },
  AMD: { flag: '🇦🇲', name: 'Armenian Dram', symbol: '֏' },
  ANG: { flag: '🇳🇱', name: 'Antillean Guilder', symbol: 'ƒ' },
  AOA: { flag: '🇦🇴', name: 'Angolan Kwanza', symbol: 'Kz' },
  AWG: { flag: '🇦🇼', name: 'Aruban Florin', symbol: 'ƒ' },
  AZN: { flag: '🇦🇿', name: 'Azerbaijani Manat', symbol: '₼' },
  BAM: { flag: '🇧🇦', name: 'Bosnian Mark', symbol: 'KM' },
  BBD: { flag: '🇧🇧', name: 'Barbadian Dollar', symbol: 'Bds$' },
  BGN: { flag: '🇧🇬', name: 'Bulgarian Lev', symbol: 'лв' },
  BHD: { flag: '🇧🇭', name: 'Bahraini Dinar', symbol: 'BD' },
  BIF: { flag: '🇧🇮', name: 'Burundian Franc', symbol: 'FBu' },
  BMD: { flag: '🇧🇲', name: 'Bermudian Dollar', symbol: 'BD$' },
  BND: { flag: '🇧🇳', name: 'Brunei Dollar', symbol: 'B$' },
  BOB: { flag: '🇧🇴', name: 'Bolivian Boliviano', symbol: 'Bs' },
  BSD: { flag: '🇧🇸', name: 'Bahamian Dollar', symbol: 'B$' },
  BTN: { flag: '🇧🇹', name: 'Bhutanese Ngultrum', symbol: 'Nu' },
  BYN: { flag: '🇧🇾', name: 'Belarusian Ruble', symbol: 'Br' },
  BZD: { flag: '🇧🇿', name: 'Belize Dollar', symbol: 'BZ$' },
  CDF: { flag: '🇨🇩', name: 'Congolese Franc', symbol: 'FC' },
  CRC: { flag: '🇨🇷', name: 'Costa Rican Colón', symbol: '₡' },
  CUP: { flag: '🇨🇺', name: 'Cuban Peso', symbol: '$MN' },
  CVE: { flag: '🇨🇻', name: 'Cape Verdean Escudo', symbol: 'Esc' },
  DJF: { flag: '🇩🇯', name: 'Djiboutian Franc', symbol: 'Fdj' },
  DOP: { flag: '🇩🇴', name: 'Dominican Peso', symbol: 'RD$' },
  DZD: { flag: '🇩🇿', name: 'Algerian Dinar', symbol: 'DA' },
  ERN: { flag: '🇪🇷', name: 'Eritrean Nakfa', symbol: 'Nfk' },
  ETB: { flag: '🇪🇹', name: 'Ethiopian Birr', symbol: 'Br' },
  FJD: { flag: '🇫🇯', name: 'Fijian Dollar', symbol: 'FJ$' },
  FKP: { flag: '🇫🇰', name: 'Falkland Pound', symbol: '£' },
  GEL: { flag: '🇬🇪', name: 'Georgian Lari', symbol: '₾' },
  GIP: { flag: '🇬🇮', name: 'Gibraltar Pound', symbol: '£' },
  GMD: { flag: '🇬🇲', name: 'Gambian Dalasi', symbol: 'D' },
  GNF: { flag: '🇬🇳', name: 'Guinean Franc', symbol: 'FG' },
  GTQ: { flag: '🇬🇹', name: 'Guatemalan Quetzal', symbol: 'Q' },
  GYD: { flag: '🇬🇾', name: 'Guyanese Dollar', symbol: 'G$' },
  HNL: { flag: '🇭🇳', name: 'Honduran Lempira', symbol: 'L' },
  HRK: { flag: '🇭🇷', name: 'Croatian Kuna', symbol: 'kn' },
  HTG: { flag: '🇭🇹', name: 'Haitian Gourde', symbol: 'G' },
  IQD: { flag: '🇮🇶', name: 'Iraqi Dinar', symbol: 'ID' },
  IRR: { flag: '🇮🇷', name: 'Iranian Rial', symbol: '﷼' },
  ISK: { flag: '🇮🇸', name: 'Icelandic Króna', symbol: 'kr' },
  JMD: { flag: '🇯🇲', name: 'Jamaican Dollar', symbol: 'J$' },
  JOD: { flag: '🇯🇴', name: 'Jordanian Dinar', symbol: 'JD' },
  KGS: { flag: '🇰🇬', name: 'Kyrgyz Som', symbol: 'лв' },
  KHR: { flag: '🇰🇭', name: 'Cambodian Riel', symbol: '៛' },
  KMF: { flag: '🇰🇲', name: 'Comorian Franc', symbol: 'CF' },
  KPW: { flag: '🇰🇵', name: 'North Korean Won', symbol: '₩' },
  KYD: { flag: '🇰🇾', name: 'Cayman Dollar', symbol: 'CI$' },
  KZT: { flag: '🇰🇿', name: 'Kazakh Tenge', symbol: '₸' },
  LAK: { flag: '🇱🇦', name: 'Lao Kip', symbol: '₭' },
  LBP: { flag: '🇱🇧', name: 'Lebanese Pound', symbol: 'LL' },
  LKR: { flag: '🇱🇰', name: 'Sri Lankan Rupee', symbol: 'Rs' },
  LRD: { flag: '🇱🇷', name: 'Liberian Dollar', symbol: 'L$' },
  LSL: { flag: '🇱🇸', name: 'Lesotho Loti', symbol: 'L' },
  LYD: { flag: '🇱🇾', name: 'Libyan Dinar', symbol: 'LD' },
  MAD: { flag: '🇲🇦', name: 'Moroccan Dirham', symbol: 'MAD' },
  MDL: { flag: '🇲🇩', name: 'Moldovan Leu', symbol: 'L' },
  MGA: { flag: '🇲🇬', name: 'Malagasy Ariary', symbol: 'Ar' },
  MKD: { flag: '🇲🇰', name: 'Macedonian Denar', symbol: 'ден' },
  MMK: { flag: '🇲🇲', name: 'Myanmar Kyat', symbol: 'K' },
  MNT: { flag: '🇲🇳', name: 'Mongolian Tugrik', symbol: '₮' },
  MOP: { flag: '🇲🇴', name: 'Macanese Pataca', symbol: 'MOP$' },
  MRU: { flag: '🇲🇷', name: 'Mauritanian Ouguiya', symbol: 'UM' },
  MUR: { flag: '🇲🇺', name: 'Mauritian Rupee', symbol: 'Rs' },
  MVR: { flag: '🇲🇻', name: 'Maldivian Rufiyaa', symbol: 'Rf' },
  MWK: { flag: '🇲🇼', name: 'Malawian Kwacha', symbol: 'MK' },
  NAD: { flag: '🇳🇦', name: 'Namibian Dollar', symbol: 'N$' },
  NIO: { flag: '🇳🇮', name: 'Nicaraguan Córdoba', symbol: 'C$' },
  NPR: { flag: '🇳🇵', name: 'Nepalese Rupee', symbol: 'Rs' },
  OMR: { flag: '🇴🇲', name: 'Omani Rial', symbol: 'OMR' },
  PAB: { flag: '🇵🇦', name: 'Panamanian Balboa', symbol: 'B/' },
  PGK: { flag: '🇵🇬', name: 'Papua New Guinean Kina', symbol: 'K' },
  PYG: { flag: '🇵🇾', name: 'Paraguayan Guarani', symbol: '₲' },
  RSD: { flag: '🇷🇸', name: 'Serbian Dinar', symbol: 'din' },
  SBD: { flag: '🇸🇧', name: 'Solomon Islands Dollar', symbol: 'SI$' },
  SCR: { flag: '🇸🇨', name: 'Seychellois Rupee', symbol: 'Rs' },
  SDG: { flag: '🇸🇩', name: 'Sudanese Pound', symbol: 'SDG' },
  SHP: { flag: '🇸🇭', name: 'Saint Helena Pound', symbol: '£' },
  SLE: { flag: '🇸🇱', name: 'Sierra Leonean Leone', symbol: 'Le' },
  SOS: { flag: '🇸🇴', name: 'Somali Shilling', symbol: 'Sh' },
  SRD: { flag: '🇸🇷', name: 'Surinamese Dollar', symbol: 'Sr$' },
  SSP: { flag: '🇸🇸', name: 'South Sudanese Pound', symbol: 'SSP' },
  STN: { flag: '🇸🇹', name: 'São Tomé Dobra', symbol: 'Db' },
  SVC: { flag: '🇸🇻', name: 'Salvadoran Colón', symbol: '₡' },
  SYP: { flag: '🇸🇾', name: 'Syrian Pound', symbol: 'LS' },
  SZL: { flag: '🇸🇿', name: 'Eswatini Lilangeni', symbol: 'E' },
  TJS: { flag: '🇹🇯', name: 'Tajik Somoni', symbol: 'SM' },
  TMT: { flag: '🇹🇲', name: 'Turkmen Manat', symbol: 'T' },
  TND: { flag: '🇹🇳', name: 'Tunisian Dinar', symbol: 'DT' },
  TOP: { flag: '🇹🇴', name: 'Tongan Paʻanga', symbol: 'T$' },
  TTD: { flag: '🇹🇹', name: 'Trinidad Dollar', symbol: 'TT$' },
  UYU: { flag: '🇺🇾', name: 'Uruguayan Peso', symbol: '$U' },
  UZS: { flag: '🇺🇿', name: 'Uzbek Som', symbol: 'soʻm' },
  VES: { flag: '🇻🇪', name: 'Venezuelan Bolívar', symbol: 'Bs.S' },
  VUV: { flag: '🇻🇺', name: 'Vanuatu Vatu', symbol: 'VT' },
  WST: { flag: '🇼🇸', name: 'Samoan Tala', symbol: 'WS$' },
  XCD: { flag: '🌍', name: 'East Caribbean Dollar', symbol: 'EC$' },
  XPF: { flag: '🌍', name: 'CFP Franc', symbol: '₣' },
  YER: { flag: '🇾🇪', name: 'Yemeni Rial', symbol: 'YR' },
  ZMW: { flag: '🇿🇲', name: 'Zambian Kwacha', symbol: 'ZK' },
  ZWL: { flag: '🇿🇼', name: 'Zimbabwean Dollar', symbol: 'Z$' },
};

/**
 * Sorted array of currencies with a pre-formatted label like
 * "🇿🇦 ZAR - South African Rand". Used by every <select> that needs a
 * currency picker (converter, settings, etc.).
 *
 * ZAR goes first, then USD/EUR/GBP, then alphabetical by code.
 */
const PRIORITY_CODES = ['ZAR', 'USD', 'EUR', 'GBP'];

export const CURRENCIES: Array<{ code: string; name: string; flag: string; label: string }> =
  Object.entries(CURRENCY_INFO)
    .map(([code, info]) => ({
      code,
      name: info.name,
      flag: info.flag,
      label: `${info.flag} ${code} - ${info.name}`,
    }))
    .sort((a, b) => {
      const ai = PRIORITY_CODES.indexOf(a.code);
      const bi = PRIORITY_CODES.indexOf(b.code);
      if (ai !== -1 && bi !== -1) return ai - bi;
      if (ai !== -1) return -1;
      if (bi !== -1) return 1;
      return a.code.localeCompare(b.code);
    });
